stages:
  - build
  - deploy

variables:
  CI_GITLAB_API_TOKEN: $CI_GITLAB_API_TOKEN
  DOCKER_REPOSITORY_IMAGE: $DOCKER_REPOSITORY_IMAGE

build:
  stage: build
  only:
    - main
    - develop
  image: $BUILD_DOCKER_IMAGE
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - >
      docker build
      --network=host -t ${DOCKER_REPOSITORY_IMAGE} .
    - docker push ${DOCKER_REPOSITORY_IMAGE}

deploy:
  stage: deploy
  only:
    - main
    - develop
  image: $DEPLOY_DOCKER_IMAGE
  script:
    - grdp-ctl

